# Generated by Django 3.2.6 on 2021-09-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('orderedBy', models.CharField(max_length=30)),
                ('assignedTo', models.ForeignKey(blank=-1, on_delete=django.db.models.deletion.CASCADE, to='home.worker')),
            ],
        ),
    ]
